- hosts: localhost 
  vars_files:
    - vars/vdirect_params.yml
    - vars/bluegreen_params.yml
  tasks:
  - name: Uploading the BlueGreen CICD workflow template to vDirect
    tags:
    - upload
    vdirect_file:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      file_name: "{{ workflow_template_file }}"
  - name: Creating CICD BlueGreen workflow
    tags:
    - create
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: WorkflowTemplate
      runnable_name: BlueGreen CICD
      parameters: {'adc':[{'type':'Adc','name': "{{ device }}"}], 'application': "{{ application }}"}
  - name: Deploying canary server
    tags:
    - deploy
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: Workflow
      action_name: deploy
      runnable_name: "{{ workflow_name}}"
      parameters: {'group':"{{ group }}", 'canary':{'id':"{{ canary_server_id }}", 'port':"{{ canary_server_port }}", 'address':"{{ canary_server_address }}", 'name': "{{ canary_server_name }}"}, 'normal_weight':"{{ normal_weight }}", 'canary_weight':"{{ canary_weight }}"}
  - name: Updating servers' weights 
    tags:
    - update
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: Workflow
      action_name: update
      runnable_name: "{{ workflow_name}}"
      parameters: {'normal_weight':"{{ normal_weight }}", 'canary_weight':"{{ canary_weight }}"}
  - name: Undeploying canary server
    tags:
    - undeploy
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: Workflow
      action_name: undeploy
      runnable_name: "{{ workflow_name}}"
  - name: Removing CICD Canary workflow 
    tags:
    - remove
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: Workflow
      action_name: deleteWorkflow
      runnable_name: "{{ workflow_name}}"
