- hosts: localhost 
  vars_files:
    - vars/vdirect_params.yml
    - vars/bluegreen_params.yml
  tasks:
  - name: Uploading the BlueGreen CICD workflow template to vDirect
    tags:
    - upload
    vdirect_file:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      file_name: "{{ workflow_template_file }}"
  - name: Creating CICD BlueGreen workflow
    tags:
    - create
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: WorkflowTemplate
      runnable_name: BlueGreen CICD
      parameters: {'adc':[{'type':'Adc','name': "{{ device }}"}], 'workflowName': "{{ workflow_name }}", 'application': "{{ application }}"}
  - name: Switching application to BLUE
    tags:
    - blue
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: Workflow
      action_name: switchToBlue
      runnable_name: "{{ workflow_name }}"
      parameters: {}
  - name: Switching application to GREEN
    tags:
    - green
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: Workflow
      action_name: switchToGreen
      runnable_name: "{{ workflow_name }}"
      parameters: {}
  - name: Removing CICD Canary workflow 
    tags:
    - remove
    vdirect_runnable:
      vdirect_ip: "{{ vdirect_ip }}"
      vdirect_user: "{{ vdirect_user }}"
      vdirect_password: "{{ vdirect_password }}"
      vdirect_validate_certs: "{{ vdirect_validate_certs }}"
      runnable_type: Workflow
      action_name: deleteWorkflow
      runnable_name: "{{ workflow_name}}"
